INSERT INTO set_menus (type, name_fr, name_nl, name_en, description_fr, description_nl, description_en, price, min_people, includes_fr, includes_nl, includes_en, display_order) VALUES
('set', 'Table de Riz du Mandarin', 'Tafel van de Mandarin', 'Mandarin Rice Table',
  'Un repas complet et généreux pour partager', 'Een compleet en overvloedig diner om te delen', 'A complete and generous meal to share',
  30.00, 2,
  '["Soupe du jour", "Dim Sum", "5 plats au choix", "Riz", "Dessert du jour"]',
  '["Soep van de dag", "Dim Sum", "5 gerechten naar keuze", "Rijst", "Dessert van de dag"]',
  '["Soup of the day", "Dim Sum", "5 dishes of your choice", "Rice", "Dessert of the day"]',
  1),
('set', 'Table de Riz Oriental', 'Oosterse Rijsttafel', 'Oriental Rice Table',
  'Le grand festin, pour les grandes tablées', 'Het grote feestmaal, voor grote gezelschappen', 'The grand feast, for large gatherings',
  27.00, 4,
  '["Soupe du jour", "Entrées au choix", "6 plats au choix", "Riz", "Dessert du jour"]',
  '["Soep van de dag", "Voorgerechten naar keuze", "6 gerechten naar keuze", "Rijst", "Dessert van de dag"]',
  '["Soup of the day", "Starters of your choice", "6 dishes of your choice", "Rice", "Dessert of the day"]',
  2),
('set', 'Menu Asia', 'Menu Asia', 'Menu Asia',
  'Le menu individuel, simple et savoureux', 'Het individueel menu, eenvoudig en smakelijk', 'The individual menu, simple and delicious',
  22.00, 1,
  '["Soupe du jour", "Entrée au choix", "Plat au choix", "Dessert du jour"]',
  '["Soep van de dag", "Voorgerecht naar keuze", "Gerecht naar keuze", "Dessert van de dag"]',
  '["Soup of the day", "Starter of your choice", "Main of your choice", "Dessert of the day"]',
  3),
('fondue', 'Fondue Cantonaise', 'Kantonese Fondue', 'Cantonese Fondue',
  '8 variétés de fruits de mer et viandes avec légumes', '8 soorten zeevruchten en vlees met groenten', '8 varieties of seafood and meats with vegetables',
  30.00, 2,
  '["Scampis", "Poisson", "Bœuf", "Poulet", "Porc", "Calamars", "Poulpe", "Moules", "Légumes du marché", "Sauce ponzu", "Bouillon maison"]',
  '["Garnalen", "Vis", "Rundvlees", "Kip", "Varken", "Pijlinktvis", "Octopus", "Mosselen", "Marktgroenten", "Ponzusaus", "Huisbouillon"]',
  '["Scampi", "Fish", "Beef", "Chicken", "Pork", "Squid", "Octopus", "Mussels", "Market vegetables", "Ponzu sauce", "House broth"]',
  1),
('fondue', 'Fondue Vietnamienne', 'Vietnamees Fondue', 'Vietnamese Fondue',
  'Fondue au bœuf et légumes, bouillon parfumé', 'Runderfondue met groenten, geurige bouillon', 'Beef and vegetable fondue, fragrant broth',
  25.00, 2,
  '["Bœuf émincé", "Légumes frais", "Vermicelles de riz", "Bouillon parfumé aux herbes", "Sauces d''accompagnement"]',
  '["Gesneden rundvlees", "Verse groenten", "Rijstvermicelli", "Kruidenbouillon", "Bijbehorende sauzen"]',
  '["Sliced beef", "Fresh vegetables", "Rice vermicelli", "Herb-infused broth", "Accompanying sauces"]',
  2);
