INSERT INTO set_menus (type, name_fr, name_nl, name_en, description_fr, description_nl, description_en, price, min_people, includes_fr, includes_nl, includes_en, display_order) VALUES
('set', 'Table de Riz du Mandarin', 'Mandarin rijsttafel', 'Mandarin rice table',
  'Potage au choix, assortiment de Dim Sum et table de riz à partager.', 'Soep naar keuze, Dim Sum-assortiment en rijsttafel om te delen.', 'Soup of your choice, Dim Sum assortment and a rice table to share.',
  30.00, 2,
  '["Potage au choix: 102, 106 ou 111", "237 - Assortiment de Dim Sum (2 pers.)", "406 - Boeuf et légumes sautés", "509 - Scampis au curry à l''Orientale", "706 - Grillades de porc laqué aux cinq parfums exotiques", "701 - Poulet grillé à la citronnelle", "602 - Riz sauté à la Cantonaise", "Dessert lychees ou kroupouk"]',
  '["Soep naar keuze: 102, 106 of 111", "237 - Dim Sum assortiment (2 pers.)", "406 - Rundvlees met gewokte groenten", "509 - Scampi in oosterse curry", "706 - Gegrild gelakt varkensvlees met vijf exotische kruiden", "701 - Gegrilde kip met citroengras", "602 - Cantonese gebakken rijst", "Dessert: lychees of kroepoek"]',
  '["Soup choice: 102, 106 or 111", "237 - Dim Sum assortment (2 people)", "406 - Beef with stir-fried vegetables", "509 - Scampi in oriental curry", "706 - Grilled lacquered pork with five exotic spices", "701 - Lemongrass grilled chicken", "602 - Cantonese fried rice", "Dessert: lychees or prawn crackers"]',
  1),
('set', 'Table de Riz Oriental', 'Oosterse rijsttafel', 'Oriental rice table',
  'Grand menu à partager avec potage, entrées au choix et six plats.', 'Grote rijsttafel om te delen met soep, keuze van voorgerechten en zes gerechten.', 'Large sharing menu with soup, choice of starters and six dishes.',
  27.00, 4,
  '["Potage au choix: 101, 102 ou 106", "Entrées au choix: assortiment d''entrées chaudes ou Dim Sum", "301 - Canard laqué à la Pékinoise", "315 - Poulet et légumes sautés", "402 - Boeuf piquant aux feuilles de basilic", "409 - Babi Pag Kang", "509 - Scampis au curry à l''Orientale", "513 - Cuisses de grenouilles au beurre et à l''ail", "602 - Riz sauté à la Cantonaise", "Dessert lychees ou kroupouk"]',
  '["Soep naar keuze: 101, 102 of 106", "Voorgerecht naar keuze: warme mix of Dim Sum", "301 - Pekingeend", "315 - Kip met gewokte groenten", "402 - Pikant rundvlees met basilicum", "409 - Babi Pag Kang", "509 - Scampi in oosterse curry", "513 - Kikkerbillen met boter en look", "602 - Cantonese gebakken rijst", "Dessert: lychees of kroepoek"]',
  '["Soup choice: 101, 102 or 106", "Starter choice: hot starter assortment or Dim Sum", "301 - Peking duck", "315 - Chicken with stir-fried vegetables", "402 - Spicy beef with basil leaves", "409 - Babi Pag Kang", "509 - Scampi in oriental curry", "513 - Frog legs with butter and garlic", "602 - Cantonese fried rice", "Dessert: lychees or prawn crackers"]',
  2),
('set', 'Menu Asia', 'Menu Asia', 'Menu Asia',
  'Menu individuel avec potage, entrée, plat et dessert au choix.', 'Individueel menu met soep, voorgerecht, hoofdgerecht en dessert naar keuze.', 'Individual menu with soup, starter, main course and dessert of your choice.',
  22.00, 1,
  '["Potage au choix: 101, 102 ou 106", "Entrée au choix: 225 ou 226", "Plat au choix: 315, 402, 513 ou 701", "Dessert lychees ou kroupouk"]',
  '["Soep naar keuze: 101, 102 of 106", "Voorgerecht naar keuze: 225 of 226", "Hoofdgerecht naar keuze: 315, 402, 513 of 701", "Dessert: lychees of kroepoek"]',
  '["Soup choice: 101, 102 or 106", "Starter choice: 225 or 226", "Main choice: 315, 402, 513 or 701", "Dessert: lychees or prawn crackers"]',
  3),
('fondue', '905 - Fondue Cantonaise', '905 - Kantonese fondue', '905 - Cantonese fondue',
  'Comprenant 8 variétés de fruits de mer et de viandes avec légumes.', 'Met 8 soorten zeevruchten en vlees met groenten.', 'Includes 8 varieties of seafood and meats with vegetables.',
  30.00, 2,
  '["8 variétés de fruits de mer et de viandes", "Légumes", "Bouillon maison"]',
  '["8 soorten zeevruchten en vlees", "Groenten", "Huisbouillon"]',
  '["8 varieties of seafood and meats", "Vegetables", "House broth"]',
  1),
('fondue', '906 - Fondue Vietnamienne', '906 - Vietnamese fondue', '906 - Vietnamese fondue',
  'Comprenant viandes de boeuf et légumes.', 'Met rundvlees en groenten.', 'Includes beef and vegetables.',
  25.00, 2,
  '["Viandes de boeuf", "Légumes", "Bouillon parfumé"]',
  '["Rundvlees", "Groenten", "Geparfumeerde bouillon"]',
  '["Beef", "Vegetables", "Fragrant broth"]',
  2);
